# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      SHOPIFY_API_KEY: 12345
      SHOPIFY_API_SECRET: 12345
      SHOP: herbomadrid-test.myshopify.com
      SCOPES: write_products,write_customers,write_draft_orders
      HOST: https://f761-82-158-184-94.ngrok.io
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      DISTRIBUDIET_USER: herbomadrid
      DISTRIBUDIET_PASSWORD: 3132lkZ1
      HEROKU_APP_DOMAIN: herbo-stock.herokuapp.com
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Setup System
        run: |
          sudo apt-get install libsqlite3-dev
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e # v1.92
        with:
          bundler-cache: true
      # Add or replace database setup steps here
      - name: Set up database schema
        run: bin/rails db:exists && bin/rails db:migrate || bin/rails db:setup
      # Add or replace test runners here
      - name: Run tests
        run: bin/rake

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e # v1.92
        with:
          bundler-cache: true
      - name: Setup Rubocop
        run: gem install rubocop
      - name: Setup Rubocop-rails
        run: gem install rubocop-rails
      - name: Lint Ruby files
        run: bundle exec rubocop --parallel --config ~/work/herbo-stock/herbo-stock/.rubocop.yml

  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e # v1.92
        with:
          bundler-cache: true
      # Add or replace any other lints here
      - name: Setup Bundle-audit
        run: gem install bundle-audit
      - name: Setup Brakeman
        run: gem install brakeman
      - name: Security audit dependencies
        run: bundler-audit --update
      - name: Security audit application code
        run: brakeman -q -w2